-- CreateEnum
CREATE TYPE "CampaignType" AS ENUM ('CONFERENCE_REMINDER', 'SERVICE_ANNOUNCEMENT', 'BIRTHDAY_GREETING', 'PASTORAL_MESSAGE', 'EMERGENCY_ANNOUNCEMENT', 'GENERAL_BROADCAST');

-- AlterTable
ALTER TABLE "Campaign" ADD COLUMN "type" "CampaignType" NOT NULL DEFAULT 'GENERAL_BROADCAST';

-- AlterTable
ALTER TABLE "VoiceMessage" ADD COLUMN "durationSeconds" INTEGER;
