-- AlterEnum
ALTER TYPE "CampaignType" ADD VALUE 'SUNDAY_SERVICE_REMINDER';
ALTER TYPE "CampaignType" ADD VALUE 'CHURCH_PROGRAMME_REMINDER';
ALTER TYPE "CampaignType" ADD VALUE 'WORKERS_MEETING_REMINDER';
ALTER TYPE "CampaignType" ADD VALUE 'CELL_FELLOWSHIP_REMINDER';
